site_name: Open3P
site_description: Open3P is an open data standard for the plastic value chain.
theme:
  name: material
  favicon: img/favicon-192.png
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: light blue 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - toc.integrate
    - navigation.top
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opendatamcr?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
      name: ODM on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opendatamcr
      name: ODM on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/OpenDataManchester
      name: ODM on GitHub
    - icon: fontawesome/brands/vimeo
      link: https://vimeo.com/opendatamcr
      name: ODM on Vimeo
    - icon: octicons/calendar-16
      link: https://www.eventbrite.co.uk/o/open-data-manchester-2263648391
      name: ODM Events
    - icon: fontawesome/solid/globe
      link: https://www.opendatamanchester.org.uk/
      name: ODM Website
repo_url: https://github.com/OpenDataManchester/PPP
repo_name: ODM/PPP
edit_uri: ""
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: True
  - attr_list


